### PR TITLE
allow doctrine/dbal ^3.3

### PR DESCRIPTION
**Pull request by cdaguerre**
fix for doctrine/dbal:3.0

### CODE REVIEW

**Comment by sload** [comment]
Hello @cdaguerre !
Thanks for the MR :-)

**Comment by cdaguerre** [comment]
@sload thanks for merging so quickly, could you publish a release?

**Comment by sload** [comment]
Done !

**Comment by LaetitiaRiffaud** [comment]
@sload The tag v0.0.6 is not available on packagist. Can you do something on your side?

**Comment by sload** [comment]
Hello @LaetitiaRiffaud , packagist is now updated.

**Pull request merged**
